sudo: false
language: cpp
compiler:
    - clang
    - gcc

before_install:
    - echo $LANG
    - echo $LC_ALL

script: make test

branches:
    only: 
        - master
        - freebsd-travis

notifications:
    email: false

os:
    - linux
    - osx
    - freebsd
