sudo: false
language: cpp
compiler:
    - clang
    - gcc

before_install:
    - echo $LANG
    - echo $LC_ALL

script: ./scripts/travis-build

branches:
    only: 
        - master

notifications:
    email: false

os:
    - linux
    - osx
    - freebsd
