name: C/C++ CI

on: [push]

jobs:
  ubuntu_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
    - uses: actions/checkout@v3
    - name: make
      env:
        CC: ${{ matrix.compiler }}
      run: make
    - name: make test
      run: make test
