name: C/C++ CI

on: [push]

strategy:
  matrix:
    compiler: [gcc, clang]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      env:
        CC: ${{ matrix.compiler }}
      run: make
    - name: make test
      run: make test
